apiVersion: argoproj.io/v2alpha1
kind: Application
metadata:
  name: guestbook6
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/ziv-codefresh/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: test-apps5
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
