apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
 name: webhook-es
spec:
 eventBusName: codefresh-eventbus
 service:
   ports:
     - port: 80
 webhook:
   # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
   example:
     # port to run HTTP server on
     port: "80"
     # endpoint to listen to
     endpoint: /webhook-es/example/
     # HTTP request method to allow. In this case, only POST requests are accepted
     method: POST
     maxPayloadSize: 8000000 #65536
